version: '3.8'

services:
  app:
    command: ["sh", "-c", "sleep 2 && gunicorn --workers 2 --timeout 300 --bind 0.0.0.0:8080 run:app"]
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:V0lBaT3rComAcaraNoposte@db:5432/biblioteca
      - SECRET_KEY=mberlyqueriaS3erohalo
    container_name: amberly
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://app:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    # Removido a seção 'deploy'

  db:
    image: postgres:13
    container_name: postgres_dba
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: V0lBaT3rComAcaraNoposte
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/conf/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d biblioteca"]
      interval: 10s
      timeout: 5s
      retries: 12
    # Removido a seção 'deploy'

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    # Removido a seção 'deploy'

volumes:
  pgdata:
