version: '3'
services:
  app:
    build: .
    container_name: amberly
    environment:
      - POSTGRES_URL=postgresql://postgres:V0lBaT3rComAcaraNoposte@db:5432/biblioteca
    depends_on:
      - db
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1G'
        reservations:
          cpus: '0.25'
          memory: '0.25G'

  db:
    image: postgres:13
    container_name: postgres_dba
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: V0lBaT3rComAcaraNoposte
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2G'  # Limite de memória para o container PostgreSQL
        reservations:
          cpus: '0.25'
          memory: '0.25G'  # Memória reservada para o container PostgreSQL

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5G'
        reservations:
          cpus: '0.125'
          memory: '0.25G'

volumes:
  pgdata:

